### ISSUE TITLE
Wondering why you are `<< 10` here: https://docs.rs/memory-stats/latest/src/memory_stats/linux.rs.html#60-61

### ISSUE THREAD

**Issue by lemonlambda** [Arc-blroth/memory-stats#4]
I am wondering why you're `<< 10` [here](https://docs.rs/memory-stats/latest/src/memory_stats/linux.rs.html#60-61) when it should be in kilobytes already right?

**Comment by Arc-blroth** [comment]
IIRC `/proc/self/statm` does in fact return sizes in kilobytes, but for consistency this library returns sizes in _bytes_ across all platforms, which is why there's the KiB-to-byte conversion in the Linux code. (both [Windows](https://learn.microsoft.com/en-us/windows/win32/api/psapi/ns-psapi-process_memory_counters_ex) and [Darwin](https://github.com/apple-oss-distributions/xnu/blob/aca3beaa3dfbd42498b42c5e5ce20a938e6554e5/osfmk/mach/task_info.h#L301) return memory info in bytes so no conversion is needed there)

**Comment by lemonlambda** [comment]
Ah okay that makes sense thank you
